-- MySQL Script generated by MySQL Workbench
-- Mon Mar  4 21:42:54 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dwellsy
-- -----------------------------------------------------
-- 
-- 
DROP SCHEMA IF EXISTS `dwellsy` ;

-- -----------------------------------------------------
-- Schema dwellsy
--
-- 
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dwellsy` DEFAULT CHARACTER SET utf8 ;
USE `dwellsy` ;

-- -----------------------------------------------------
-- Table `dwellsy`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dwellsy`.`users` ;

CREATE TABLE IF NOT EXISTS `dwellsy`.`users` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `email` VARCHAR(128) NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwellsy`.`communities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dwellsy`.`communities` ;

CREATE TABLE IF NOT EXISTS `dwellsy`.`communities` (
  `communityId` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`communityId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwellsy`.`properties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dwellsy`.`properties` ;

CREATE TABLE IF NOT EXISTS `dwellsy`.`properties` (
  `propertyId` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NULL,
  `houseNumber` VARCHAR(45) NULL,
  `unitNumber` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `postalCode` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `lat` FLOAT NULL,
  `long` FLOAT NULL,
  `sqft` INT NULL,
  `bedroomNumber` INT NULL,
  `fullBathroomNumber` INT NULL,
  `halfBathroomNumber` INT NULL,
  `parkingSpacesIncludedNumber` INT NULL,
  `parkingSpacesAvailableNumber` INT NULL,
  `communityId` INT NULL,
  `claimedBy` INT NOT NULL,
  PRIMARY KEY (`propertyId`),
  INDEX `fk_properties_1_idx` (`communityId` ASC),
  INDEX `fk_properties_2_idx` (`claimedBy` ASC),
  CONSTRAINT `fk_properties_1`
    FOREIGN KEY (`communityId`)
    REFERENCES `dwellsy`.`communities` (`communityId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_properties_2`
    FOREIGN KEY (`claimedBy`)
    REFERENCES `dwellsy`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwellsy`.`userfavorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dwellsy`.`userfavorites` ;

CREATE TABLE IF NOT EXISTS `dwellsy`.`userfavorites` (
  `userId` INT NOT NULL,
  `propertyId` INT NOT NULL,
  INDEX `fk_userfavorites_1_idx` (`userId` ASC),
  INDEX `fk_userfavorites_2_idx` (`propertyId` ASC),
  CONSTRAINT `fk_userfavorites_1`
    FOREIGN KEY (`userId`)
    REFERENCES `dwellsy`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userfavorites_2`
    FOREIGN KEY (`propertyId`)
    REFERENCES `dwellsy`.`properties` (`propertyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwellsy`.`userdeletes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dwellsy`.`userdeletes` ;

CREATE TABLE IF NOT EXISTS `dwellsy`.`userdeletes` (
  `userId` INT NOT NULL,
  `propertyId` INT NOT NULL,
  INDEX `fk_userfavorites_1_idx` (`userId` ASC),
  INDEX `fk_userfavorites_2_idx` (`propertyId` ASC),
  CONSTRAINT `fk_userdeletes_1`
    FOREIGN KEY (`userId`)
    REFERENCES `dwellsy`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userdeletes_2`
    FOREIGN KEY (`propertyId`)
    REFERENCES `dwellsy`.`properties` (`propertyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwellsy`.`amenityTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dwellsy`.`amenityTypes` ;

CREATE TABLE IF NOT EXISTS `dwellsy`.`amenityTypes` (
  `amenityTypeId` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `appliesToProperty` TINYINT(1) NOT NULL,
  `appliesToCommunity` TINYINT(1) NOT NULL,
  PRIMARY KEY (`amenityTypeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwellsy`.`propertyAmenities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dwellsy`.`propertyAmenities` ;

CREATE TABLE IF NOT EXISTS `dwellsy`.`propertyAmenities` (
  `propertyId` INT NOT NULL,
  `amenityityType` INT NULL,
  `amenityValue` INT NULL,
  PRIMARY KEY (`propertyId`),
  INDEX `fk_propertyAmenities_2_idx` (`amenityityType` ASC),
  CONSTRAINT `fk_propertyAmenities_1`
    FOREIGN KEY (`propertyId`)
    REFERENCES `dwellsy`.`properties` (`propertyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_propertyAmenities_2`
    FOREIGN KEY (`amenityityType`)
    REFERENCES `dwellsy`.`amenityTypes` (`amenityTypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwellsy`.`communityAmenities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dwellsy`.`communityAmenities` ;

CREATE TABLE IF NOT EXISTS `dwellsy`.`communityAmenities` (
  `communityId` INT NOT NULL,
  `amentiyType` INT NULL,
  `amenityValue` INT NULL,
  INDEX `fk_communityAmenities_1_idx` (`communityId` ASC),
  INDEX `fk_communityAmenities_2_idx` (`amentiyType` ASC),
  CONSTRAINT `fk_communityAmenities_1`
    FOREIGN KEY (`communityId`)
    REFERENCES `dwellsy`.`communities` (`communityId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_communityAmenities_2`
    FOREIGN KEY (`amentiyType`)
    REFERENCES `dwellsy`.`amenityTypes` (`amenityTypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dwellsy`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dwellsy`.`media` ;

CREATE TABLE IF NOT EXISTS `dwellsy`.`media` (
  `mediaId` INT NOT NULL,
  `propertyId` INT NULL,
  `url` VARCHAR(128) NULL,
  `type` INT NULL,
  `tagId` INT NULL,
  PRIMARY KEY (`mediaId`),
  INDEX `fk_media_1_idx` (`propertyId` ASC),
  CONSTRAINT `fk_media_1`
    FOREIGN KEY (`propertyId`)
    REFERENCES `dwellsy`.`properties` (`propertyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO dwellsy;
 DROP USER dwellsy;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'dwellsy' IDENTIFIED BY 'dwellsy';

GRANT ALL ON `dwellsy`.* TO 'dwellsy';
GRANT SELECT ON TABLE `dwellsy`.* TO 'dwellsy';
GRANT SELECT, INSERT, TRIGGER ON TABLE `dwellsy`.* TO 'dwellsy';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `dwellsy`.* TO 'dwellsy';
GRANT EXECUTE ON ROUTINE `dwellsy`.* TO 'dwellsy';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

